CREATE DATABASE IF NOT EXISTS sistema_cadastro;
USE sistema_cadastro;

CREATE TABLE usuarios (
ID CHAR PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
telefone VARCHAR(200) NOT NULL,
endereco VARCHAR(100) NOT NULL,
estado CHAR(2) NOT NULL,
data_nascimento DATE NOT NULL, 
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);